### ISSUE TITLE
Spurious access denied errors on Windows

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#775]
On Windows, we're seeing intermittent access denied errors in some of our cross-validation tests. They're happening when we are trying to `Files.move` the temporary file to its final location for an atomic file update. From [build 3.0.327](https://ci.appveyor.com/project/elehack/lenskit/build/3.0.327):

```
Caused by: java.nio.file.AccessDeniedException: cache\.tmp.e7d95bdb-1cc7-4b72-b79e-8349c6d33627.e8770d236d89c7b1e3032111c78ce41c0a0be4a6.dat.gz -> cache\e8770d236d89c7b1e3032111c78ce41c0a0be4a6.dat.gz
    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[na:1.7.0_79]
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[na:1.7.0_79]
    at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301) ~[na:1.7.0_79]
    at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[na:1.7.0_79]
    at java.nio.file.Files.move(Files.java:1347) ~[na:1.7.0_79]
    at org.lenskit.util.io.StagedWrite.commit(StagedWrite.java:134) ~[lenskit-core-3.0-20150911.170721-1.jar:na]
    at org.grouplens.lenskit.eval.traintest.ComponentCache$CacheEntry.writeCompressedObject(ComponentCache.java:285) ~[lenskit-eval-3.0-20150911.170722-1.jar:na]
    at org.grouplens.lenskit.eval.traintest.ComponentCache$CacheEntry.getObject(ComponentCache.java:263) ~[lenskit-eval-3.0-20150911.170722-1.jar:na]
    at org.grouplens.lenskit.eval.traintest.ComponentCache.processNode(ComponentCache.java:168) ~[lenskit-eval-3.0-20150911.170722-1.jar:na]
    ... 7 common frames omitted
```

**Comment by mdekstrand** [comment]
I have not seen this error in quite some time.
