### ISSUE TITLE
An exception when test and train folds are disjoint

### ISSUE THREAD

**Issue by jumutc** [lenskit/lenskit#838]
Hello, 
When I execute ``TrainTestExperiment`` with ``PredictEvalTask`` I get an exception when my rating matrix is small and cross-validation leads to the disjoint test and train folds:
```
org.lenskit.eval.traintest.EvaluationException: error running evaluation
	at org.lenskit.eval.traintest.TrainTestExperiment.runJobList(TrainTestExperiment.java:543)
	at org.lenskit.eval.traintest.TrainTestExperiment.execute(TrainTestExperiment.java:382)
	at ...
Caused by: java.lang.NullPointerException: null
	at org.lenskit.eval.traintest.predict.PredictEvalTask$PredictConditionEvaluator.finish(PredictEvalTask.java:301)
	at org.lenskit.eval.traintest.ExperimentJob.run(ExperimentJob.java:181)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 common frames omitted
```

I have fixed it with a small modification in the ``finish`` method of ```PredictEvalTask``` but it would be nice to have it in the ``lenskit`` framework codebase as well.

**Comment by mdekstrand** [comment]
Thanks for filing this!

I can take a look at it, but if you'd like to submit your fix as a pull request, I'd gladly consider integrating it directly.

Could you say a bit more about exactly how your train/test folds are disjoint? Are there users in testing that aren't in training, or items?

**Comment by jumutc** [comment]
Thank you for a quick response! I will probably submit my pull request because for my project I had to reimplement ``PredictEvalTask`` to fix the problem. You are indeed right -> in test there are users which are not present in train but ``java.lang.NullPointerException`` occurs only when entire test set is unseen by the trained model.

**Comment by jumutc** [comment]
Thank you for merging!
